-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Nov 06, 2025 at 11:04 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `maruti`
--

-- --------------------------------------------------------

--
-- Table structure for table `pro`
--

CREATE TABLE `pro` (
  `id` int(100) NOT NULL,
  `name` text NOT NULL,
  `image` text NOT NULL,
  `content` text NOT NULL,
  `slug` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `pro`
--

INSERT INTO `pro` (`id`, `name`, `image`, `content`, `slug`) VALUES
(1, 'Spices', 'image/pro/p (1).jpg', '<div class=\"\">\r\n    <h3 class=\"title\">Spices</h3>\r\n\r\n    <p>\r\n        <strong>Maruti International</strong> is a trusted supplier of premium-quality <strong>spices</strong> sourced from the finest farms across India. We offer a wide range of spices including <strong>turmeric, cumin, coriander, black pepper, cardamom, cloves, cinnamon, chili, and fenugreek</strong>. Our spices are carefully selected, cleaned, and processed to maintain their natural aroma, flavor, and nutritional benefits.\r\n    </p>\r\n\r\n    <p>\r\n        Our spices are known for their rich flavors, high essential oil content, and purity. They are widely used in culinary applications, food processing, and health remedies. At <strong>Maruti International</strong>, we work closely with farmers to ensure sustainable and ethical sourcing practices, guaranteeing fresh and authentic spices for domestic and international markets.\r\n    </p>\r\n\r\n    <p>\r\n        We take pride in offering spices that are <strong>100% natural, chemical-free, and non-GMO</strong>. Our quality control team rigorously tests for purity, moisture content, and microbial safety before packaging. Flexible packaging options such as 25kg, 50kg, and customized bags are available to cater to wholesalers, food manufacturers, and retailers worldwide.\r\n    </p>\r\n\r\n    <br>\r\n    <h4>Key Features & Benefits</h4>\r\n    <p>Our spices are recognized for their authenticity, nutritional value, and culinary versatility.</p>\r\n\r\n    <ul class=\"list-style-one mt-25\">\r\n        <li>Wide variety of Indian spices – Turmeric, Cumin, Coriander, Black Pepper, Cardamom, Cloves, Cinnamon, Chili, Fenugreek</li>\r\n        <li>Rich in antioxidants, essential oils, and natural flavors</li>\r\n        <li>100% natural, non-GMO, and free from harmful chemicals</li>\r\n        <li>Carefully cleaned, graded, and packed under hygienic conditions</li>\r\n        <li>Ideal for cooking, seasoning, herbal remedies, and food processing</li>\r\n        <li>Custom packaging options for bulk export and retail distribution</li>\r\n        <li>Compliant with international food safety and export standards</li>\r\n        <li>Sustainably sourced from trusted Indian farmers</li>\r\n    </ul>\r\n\r\n    <p>\r\n        At <strong>Maruti International</strong>, we aim to bring the authentic taste and health benefits of Indian spices to kitchens around the world. With a focus on quality, consistency, and customer satisfaction, we continue to be a reliable partner for businesses and consumers seeking high-quality spices.\r\n    </p>\r\n</div>\r\n', 'spices'),
(2, 'Potatoes', 'image/pro/p (3).jpg', '<div class=\"\">\n    <h3 class=\"title\">Potatoes</h3>\n\n    <p>\n        <strong>Maruti International</strong> is a trusted supplier of premium-quality <strong>potatoes</strong>, sourced from the best farms across India. We provide a wide range of potato varieties suitable for different culinary and processing needs, including fresh table potatoes and varieties for chips, fries, and other food industries. Our potatoes are carefully selected to ensure uniform size, quality, and freshness.\n    </p>\n\n    <p>\n        Our potatoes are known for their excellent taste, texture, and high nutritional value. They are rich in carbohydrates, dietary fiber, vitamin C, and essential minerals, making them a staple food for households and an essential ingredient for food processing. At <strong>Maruti International</strong>, we work closely with farmers to ensure sustainable and ethical sourcing practices, guaranteeing fresh and high-quality potatoes for domestic and international markets.\n    </p>\n\n    <p>\n        We take pride in offering potatoes that are <strong>fresh, chemical-free, and carefully handled</strong>. Our quality control team ensures that every batch meets stringent standards for size, firmness, and quality. Flexible packaging options such as 25kg, 50kg, and customized bags are available to meet the needs of wholesalers, retailers, and food manufacturers worldwide.\n    </p>\n\n    <br>\n    <h4>Key Features & Benefits</h4>\n    <p>Our potatoes are valued for their freshness, quality, and versatility in global cuisines.</p>\n\n    <ul class=\"list-style-one mt-25\">\n        <li>High-quality Indian potatoes, suitable for cooking, frying, and processing</li>\n        <li>Fresh, firm, and free from blemishes or damage</li>\n        <li>Rich in carbohydrates, fiber, vitamin C, and essential minerals</li>\n        <li>Carefully cleaned, sorted, and packed under hygienic conditions</li>\n        <li>Ideal for households, restaurants, and food processing industries</li>\n        <li>Custom packaging options for bulk export and retail distribution</li>\n        <li>Compliant with food safety and export standards</li>\n        <li>Sustainably sourced from trusted Indian farmers</li>\n    </ul>\n\n    <p>\n        At <strong>Maruti International</strong>, we strive to deliver the best quality potatoes consistently, ensuring that our customers receive fresh, nutritious, and flavorful produce. With a focus on quality, reliability, and customer satisfaction, we continue to be a dependable supplier for both domestic and international markets.\n    </p>\n</div>\n', 'potatoes'),
(3, 'Rice', 'image/pro/p (4).jpg', '<div class=\"\">\r\n    <h3 class=\"title\">Rice</h3>\r\n\r\n    <p>\r\n        <strong>Maruti International</strong> is a trusted supplier of premium-quality <strong>Indian rice</strong>, sourced from the fertile fields of India. We offer a wide range of rice varieties including <strong>Basmati, Sona Masoori, Ponni, Jasmine, and Non-Basmati rice</strong>, catering to both domestic consumption and international markets. Our rice is carefully harvested, cleaned, and processed to maintain its natural aroma, taste, and nutritional value.\r\n    </p>\r\n\r\n    <p>\r\n        Our rice is known for its superior quality, long grains, and rich flavor. It is a staple food that provides essential carbohydrates, protein, and energy. At <strong>Maruti International</strong>, we work closely with farmers to ensure sustainable and ethical sourcing practices, delivering rice that meets global quality standards and consumer expectations.\r\n    </p>\r\n\r\n    <p>\r\n        We take pride in providing rice that is <strong>100% natural, non-GMO, and free from harmful chemicals</strong>. Each batch undergoes rigorous quality checks for purity, moisture content, and uniformity. Flexible packaging options such as 25kg, 50kg, and customized export bags are available to meet the needs of wholesalers, retailers, and food manufacturers worldwide.\r\n    </p>\r\n\r\n    <br>\r\n    <h4>Key Features & Benefits</h4>\r\n    <p>Our rice is valued for its purity, nutritional content, and versatility in global cuisines.</p>\r\n\r\n    <ul class=\"list-style-one mt-25\">\r\n        <li>Wide range of Indian rice – Basmati, Sona Masoori, Ponni, Jasmine, Non-Basmati</li>\r\n        <li>Long grains, aromatic flavor, and excellent cooking quality</li>\r\n        <li>Rich in carbohydrates, protein, and essential nutrients</li>\r\n        <li>Carefully cleaned, sorted, and packed under hygienic conditions</li>\r\n        <li>Ideal for households, restaurants, and food processing industries</li>\r\n        <li>Custom packaging options for bulk export and retail distribution</li>\r\n        <li>Compliant with international food safety and export standards</li>\r\n        <li>Sustainably sourced from trusted Indian farmers</li>\r\n    </ul>\r\n\r\n    <p>\r\n        At <strong>Maruti International</strong>, we aim to provide high-quality rice that meets the diverse needs of our customers. With a focus on consistency, reliability, and customer satisfaction, we continue to be a dependable supplier for domestic and international markets.\r\n    </p>\r\n</div>\r\n', 'rice'),
(4, 'Pulses', 'image/pro/p (6).jpg', '<div class=\"\">\r\n    <h3 class=\"title\">Pulses</h3>\r\n\r\n    <p>\r\n        <strong>Maruti International</strong> is a trusted supplier of premium-quality <strong>Indian pulses</strong>, sourced from the best farms across India. We offer a wide range of pulses including <strong>lentils (masoor), chickpeas (chana), pigeon peas (toor), green gram (moong), black gram (urad), kidney beans (rajma), and peas</strong>. Our pulses are carefully cleaned, sorted, and processed to ensure maximum purity, nutritional value, and consistency.\r\n    </p>\r\n\r\n    <p>\r\n        Pulses are a rich source of protein, dietary fiber, vitamins, and essential minerals, making them a staple in vegetarian and health-conscious diets. At <strong>Maruti International</strong>, we work closely with farmers to ensure sustainable and ethical sourcing practices, delivering pulses that meet international quality standards and consumer expectations.\r\n    </p>\r\n\r\n    <p>\r\n        We take pride in offering pulses that are <strong>100% natural, chemical-free, and non-GMO</strong>. Each batch undergoes rigorous testing for purity, moisture content, and microbial safety. Flexible packaging options such as 25kg, 50kg, and customized export bags are available to meet the needs of wholesalers, retailers, and food manufacturers worldwide.\r\n    </p>\r\n\r\n    <br>\r\n    <h4>Key Features & Benefits</h4>\r\n    <p>Our pulses are recognized for their nutritional richness, quality, and versatility in global cuisines.</p>\r\n\r\n    <ul class=\"list-style-one mt-25\">\r\n        <li>Wide variety of Indian pulses – Masoor, Chana, Toor, Moong, Urad, Rajma, Peas</li>\r\n        <li>High in protein, dietary fiber, vitamins, and essential minerals</li>\r\n        <li>100% natural, non-GMO, and free from harmful chemicals</li>\r\n        <li>Carefully cleaned, graded, and packed under hygienic conditions</li>\r\n        <li>Ideal for home cooking, ready-to-eat meals, and food processing</li>\r\n        <li>Custom packaging options for bulk export and retail distribution</li>\r\n        <li>Compliant with international food safety and export standards</li>\r\n        <li>Sustainably sourced from trusted Indian farmers</li>\r\n    </ul>\r\n\r\n    <p>\r\n        At <strong>Maruti International</strong>, we are committed to delivering high-quality pulses that support a healthy and balanced diet. With a focus on reliability, consistency, and customer satisfaction, we continue to be a dependable supplier for both domestic and international markets.\r\n    </p>\r\n</div>\r\n', 'pulses'),
(5, 'Fruits', 'image/pro/p.jpg', '<div class=\"\">\r\n    <h3 class=\"title\">Fruits</h3>\r\n\r\n    <p>\r\n        <strong>Maruti International</strong> is a trusted supplier of fresh and premium-quality <strong>fruits</strong>, sourced from the best orchards and farms across India. We offer a wide range of fruits including <strong>apples, bananas, oranges, mangoes, pomegranates, grapes, papayas, and seasonal fruits</strong>. Our fruits are carefully selected to ensure freshness, taste, and nutritional value.\r\n    </p>\r\n\r\n    <p>\r\n        Our fruits are packed with essential vitamins, minerals, and antioxidants, making them an integral part of a healthy and balanced diet. At <strong>Maruti International</strong>, we work closely with farmers to ensure sustainable and ethical sourcing practices, delivering fruits that meet global quality standards and customer expectations.\r\n    </p>\r\n\r\n    <p>\r\n        We take pride in offering fruits that are <strong>fresh, natural, and free from harmful chemicals</strong>. Each batch undergoes strict quality checks for ripeness, firmness, and flavor. Flexible packaging options are available to cater to wholesalers, retailers, and exporters, ensuring that fruits reach customers in perfect condition.\r\n    </p>\r\n\r\n    <br>\r\n    <h4>Key Features & Benefits</h4>\r\n    <p>Our fruits are celebrated for their freshness, nutritional richness, and versatility in consumption.</p>\r\n\r\n    <ul class=\"list-style-one mt-25\">\r\n        <li>Wide variety of Indian fruits – Apples, Bananas, Oranges, Mangoes, Pomegranates, Grapes, Papayas, and seasonal fruits</li>\r\n        <li>Rich in vitamins, minerals, antioxidants, and dietary fiber</li>\r\n        <li>100% fresh, natural, and free from harmful chemicals</li>\r\n        <li>Carefully sorted, packed, and handled under hygienic conditions</li>\r\n        <li>Ideal for households, retail, and food processing industries</li>\r\n        <li>Custom packaging options for bulk export and distribution</li>\r\n        <li>Compliant with international food safety and export standards</li>\r\n        <li>Sustainably sourced from trusted Indian farmers and orchards</li>\r\n    </ul>\r\n\r\n    <p>\r\n        At <strong>Maruti International</strong>, we are committed to delivering fresh, high-quality fruits consistently. With a strong focus on quality, reliability, and customer satisfaction, we continue to be a dependable supplier for domestic and international markets.\r\n    </p>\r\n</div>\r\n', 'fruits');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `pro`
--
ALTER TABLE `pro`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `pro`
--
ALTER TABLE `pro`
  MODIFY `id` int(100) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
