-- phpMyAdmin SQL Dump
-- version 5.2.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Jan 12, 2026 at 05:50 AM
-- Server version: 11.8.3-MariaDB-log
-- PHP Version: 7.2.34

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `u496524825_lmok`
--

-- --------------------------------------------------------

--
-- Table structure for table `blog`
--

CREATE TABLE `blog` (
  `id` int(100) NOT NULL,
  `tag` text NOT NULL,
  `heading` varchar(200) NOT NULL,
  `content` text NOT NULL,
  `image` varchar(256) NOT NULL,
  `date` date NOT NULL,
  `slug` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `blog`
--

INSERT INTO `blog` (`id`, `tag`, `heading`, `content`, `image`, `date`, `slug`) VALUES
(426, '<meta name=\"description\" content=\"LMOK Global Trade is a trusted Groundnut exporter in Vietnam, offering premium-quality groundnuts with reliable global supply.\"> <meta name=\"keywords\" content=\"Groundnut exporter in Vietnam\" />', 'Trusted Groundnut Exporter in Vietnam for Quality ', '<span id=\"docs-internal-guid-6dec8aec-7fff-aab4-4016-6a49e900ffb6\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:12pt;margin-bottom:12pt;\"><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">LMOK Global Trade is a trusted </span><span style=\"text-decoration-line: underline; font-size: 11pt; font-family: Arial, sans-serif; color: rgb(17, 85, 204); background-color: transparent; font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space-collapse: preserve;\"><a href=\"https://lmokglobaltrade.com/blog/groundnut-exporter-in-vietnam\">Groundnut exporter in Vietnam</a></span><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">, delivering premium-quality groundnuts to global markets with strict quality checks and reliable supply systems. We ensure freshness, purity, and consistent grading for every shipment. With a strong sourcing network and international export standards, LMOK Global Trade stands out as a dependable partner for importers seeking high-quality Vietnam groundnuts.</span></p></span>', 'blog/img_694d24e0d17960.20090313.webp', '2025-12-25', 'groundnut-exporter-in-vietnam'),
(427, '<meta name=\"description\" content=\"LMOK Global Trade – Premium Groundnut supplier in Canada offering high-quality groundnuts with reliable delivery for businesses.\"> <meta name=\"keywords\" content=\"Groundnut supplier in Canada\" />', 'Premium Groundnut Supplier in Canada for Businesses', '<span id=\"docs-internal-guid-4cc83700-7fff-1003-fe42-f7cec9f77a62\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:12pt;margin-bottom:12pt;\"><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">LMOK Global Trade is a leading </span><span style=\"text-decoration-line: underline; font-size: 11pt; font-family: Arial, sans-serif; color: rgb(17, 85, 204); font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space-collapse: preserve;\"><a href=\"https://lmokglobaltrade.com/blog/groundnut-supplier-in-canada\">Groundnut supplier in Canada</a></span><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">, delivering premium-grade groundnuts tailored for businesses, wholesalers, and food manufacturers. As a trusted name in quality and reliability, we ensure hygienic processing, strict quality control, and timely delivery across Canada. Partner with us for consistently fresh, high-grade groundnuts that support your production needs and business growth.</span></p></span>', 'blog/img_694e4a669f6c80.74247886.webp', '2025-12-26', 'groundnut-supplier-in-canada'),
(428, '<meta name=\"description\" content=\"LMOK Global Trade – High-quality groundnut exporter in UK offering pure, fresh peanuts with fast delivery and reliable global supply.\"> <meta name=\"keywords\" content=\"Groundnut exporter in UK\" />', 'High-Quality Groundnut Exporter in UK | Fast Delivery', '<span id=\"docs-internal-guid-2f248418-7fff-b9a2-d6c1-e74c1fd4bba4\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:12pt;margin-bottom:12pt;\"><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">LMOK Global Trade</span><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\"> is a leading </span><span style=\"text-decoration-line: underline; font-size: 10pt; font-family: Arial, sans-serif; color: rgb(17, 85, 204); font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space-collapse: preserve;\"><a href=\"https://lmokglobaltrade.com/blog/groundnut-exporter-in-uk\">Groundnut exporter in UK</a></span><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">, delivering premium-quality peanuts to global buyers with fast, reliable shipping. We ensure freshness, purity, and strict quality standards in every batch. Whether you need bulk quantities or customized packaging, our team provides seamless service, competitive pricing, and timely delivery. Choose LMOK Global Trade for trusted groundnut supply across international markets.</span></p></span>', 'blog/img_694e4ab0cf2c46.04925593.webp', '2025-12-26', 'groundnut-exporter-in-uk'),
(429, '<meta name=\"description\" content=\"LMOK Global Trade is a trusted Groundnut exporter in Malaysia, offering premium-quality peanuts with reliable global delivery.\"> <meta name=\"keywords\" content=\"Groundnut exporter in Malaysia\" />', 'Premium Groundnut Exporter in Malaysia for Importers ', '<span id=\"docs-internal-guid-d28dc176-7fff-3b06-476c-78675af16c54\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:12pt;margin-bottom:12pt;\"><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">LMOK Global Trade is a leading </span><span style=\"text-decoration-line: underline; font-size: 11pt; font-family: Arial, sans-serif; color: rgb(17, 85, 204); font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space-collapse: preserve;\"><a href=\"https://lmokglobaltrade.com/blog/groundnut-exporter-in-malaysia\">Groundnut exporter in Malaysia</a></span><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">, delivering premium-quality peanuts to global importers with guaranteed freshness and strict quality control. As a premium groundnut exporter in Malaysia, we offer consistent supply, competitive pricing, and reliable international shipping. LMOK Global Trade is committed to providing naturally sourced, hygienically processed groundnuts tailored to meet the needs of worldwide buyers.</span></p></span>', 'blog/img_694e4af48d2a97.25864899.webp', '2025-12-26', 'groundnut-exporter-in-malaysia'),
(430, '<meta name=\"description\" content=\"LMOK Global Trade is a trusted Groundnut exporter in France offering premium quality peanuts and reliable global bulk supply.\"> <meta name=\"keywords\" content=\"Groundnut exporter in France\" />', 'Leading Groundnut Exporter in France for Global Trade', '<span id=\"docs-internal-guid-3bdaaa23-7fff-e3ca-4cbd-9f3fde5e2757\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:12pt;margin-bottom:12pt;\"><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">LMOK Global Trade is a trusted </span><span style=\"text-decoration-line: underline; font-size: 11pt; font-family: Arial, sans-serif; color: rgb(17, 85, 204); font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space-collapse: preserve;\"><a href=\"https://lmokglobaltrade.com/blog/groundnut-exporter-in-france\">Groundnut exporter in France</a></span><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">, delivering high-quality peanuts to international markets with consistency and care. As a leading Groundnut Exporter in France for Global Trade, we ensure premium grading, hygienic processing, and timely shipment for all bulk orders. LMOK Global Trade is committed to excellence, reliability, and long-term global partnerships.</span></p></span>', 'blog/img_694e4b1d501604.26213195.webp', '2025-12-26', 'groundnut-exporter-in-france'),
(431, '<meta name=\"description\" content=\"LMOK Global Trade is a top Spices exporter in UAE offering premium quality spices with reliable worldwide delivery.\"> <meta name=\"keywords\" content=\"Spices exporter in UAE\" />', 'Quality Spices Exporter in UAE for Worldwide Delivery', '<span id=\"docs-internal-guid-705384bb-7fff-8415-407d-146112ad8702\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:12pt;margin-bottom:12pt;\"><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">LMOK Global Trade, a leading </span><span style=\"text-decoration-line: underline; font-size: 11pt; font-family: Arial, sans-serif; color: rgb(17, 85, 204); font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space-collapse: preserve;\"><a href=\"https://lmokglobaltrade.com/blog/spices-exporter-in-uae\">Spices exporter in UAE</a></span><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">, delivers premium-quality spices sourced from trusted farms and processed to global standards. We ensure freshness, purity, and consistent flavor in every shipment. With worldwide delivery, reliable packaging, and competitive pricing, LMOK Global Trade is committed to supplying authentic spices that meet international market demands. Partner with us for quality you can trust.</span></p></span>', 'blog/img_694e4b47ee88a9.75698155.webp', '2025-12-26', 'spices-exporter-in-uae'),
(432, '<meta name=\"description\" content=\"LMOK Global Trade – Trusted Spices Supplier in Germany offering premium, pure, and bulk spices for businesses and industries.\"> <meta name=\"keywords\" content=\"Spices supplier in Germany\" />', 'Premium Spices Supplier in Germany for Businesses ', '<span id=\"docs-internal-guid-f2ec382e-7fff-7759-f0a1-22c79859b04f\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:12pt;margin-bottom:12pt;\"><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">LMOK Global Trade is a trusted </span><span style=\"text-decoration-line: underline; font-size: 11pt; font-family: Arial, sans-serif; color: rgb(17, 85, 204); font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space-collapse: preserve;\"><a href=\"https://lmokglobaltrade.com/blog/spices-supplier-in-germany\">Spices Supplier in Germany</a></span><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">, delivering premium-grade spices tailored for businesses, wholesalers, and food manufacturers. As a Premium Spices Supplier in Germany for Businesses, we ensure purity, rich aroma, and consistent quality in every batch. LMOK Global Trade specializes in bulk supply, timely delivery, and globally sourced authentic spices to support your production needs with reliability and excellence.</span></p></span>', 'blog/img_694e4bc5ae9f47.16649678.webp', '2025-12-26', 'spices-supplier-in-germany'),
(433, '<meta name=\"description\" content=\"Premium Spices Exporter in France. LMOK Global Trade supplies top-quality spices for global importers with reliable delivery.\"> <meta name=\"keywords\" content=\"Spices exporter in France\" />', 'Premium Spices Exporter in France for Importers', '<span id=\"docs-internal-guid-1cadd084-7fff-5c24-e2ca-fbc67a75c61b\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:12pt;margin-bottom:12pt;\"><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">LMOK Global Trade is a leading </span><span style=\"text-decoration-line: underline; font-size: 10pt; font-family: Arial, sans-serif; color: rgb(17, 85, 204); font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space-collapse: preserve;\"><a href=\"https://lmokglobaltrade.com/blog/spices-exporter-in-france\">Spices Exporter in France</a></span><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">, delivering premium-quality spices to global importers. We specialize in sourcing, processing, and exporting aromatic, high-grade spices that meet international standards. With reliable logistics, consistent supply, and competitive pricing, LMOK Global Trade ensures every importer receives top-quality products with exceptional freshness and flavor. Your trusted partner for bulk spice exports in France.</span></p></span>', 'blog/img_694e4c0a6f3220.76628283.webp', '2025-12-26', 'spices-exporter-in-france'),
(434, '<meta name=\"description\" content=\"LMOK Global Trade—Leading Spices exporter in Thailand delivering premium, authentic spices for reliable global trade and bulk supply.\"> <meta name=\"keywords\" content=\"Spices exporter in Thailand\" />', 'Top Spices Exporter in Thailand for International Trade', '<span id=\"docs-internal-guid-26e1f49e-7fff-417f-8478-6cf4049b4629\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:12pt;margin-bottom:12pt;\"><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">LMOK Global Trade is a top </span><span style=\"text-decoration-line: underline; font-size: 10pt; font-family: Arial, sans-serif; color: rgb(17, 85, 204); font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space-collapse: preserve;\"><a href=\"https://lmokglobaltrade.com/blog/spices-exporter-in-thailand\">Spices exporter in Thailand</a></span><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">, delivering premium-quality spices to international buyers with unmatched reliability. As a leading name in global trade, the company ensures fresh, authentic, and carefully sourced spices that meet global standards. With strong supply chain expertise and commitment to excellence, LMOK Global Trade supports businesses worldwide seeking consistent and trusted spice exports from Thailand.</span></p><div bis_skin_checked=\"1\"><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\"><br></span></div></span>', 'blog/img_694e4c3c087ac5.88280030.webp', '2025-12-26', 'spices-exporter-in-thailand'),
(435, '<meta name=\"description\" content=\"LMOK Global Trade is a trusted Spices Supplier in Canada, offering premium quality spices for global traders with fast delivery.\"> <meta name=\"keywords\" content=\"Spices supplier in Canada\" />', 'Canada’s Best Spices Supplier for Global Traders ', '<span id=\"docs-internal-guid-b5942c56-7fff-e11e-d8b6-be9c5f888448\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:12pt;margin-bottom:12pt;\"><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">LMOK Global Trade, a leading </span><span style=\"text-decoration-line: underline; font-size: 11pt; font-family: Arial, sans-serif; color: rgb(17, 85, 204); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space-collapse: preserve;\"><a href=\"https://lmokglobaltrade.com/blog/spices-supplier-in-canada\">Spices Supplier in Canada</a></span><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">, delivers premium, pure, and internationally certified spices for global traders. As Canada’s Best Spices Supplier for Global Traders, we provide consistent quality, competitive pricing, and reliable export services. From bulk orders to customized packaging, LMOK Global Trade ensures freshness, authenticity, and timely delivery to meet international market demands.</span></p></span>', 'blog/img_694e4c67486e20.43752051.webp', '2025-12-26', 'spices-supplier-in-canada'),
(436, '<meta name=\"description\" content=\"Premium Millets exporter in Indonesia offering high-quality bulk supply. LMOK Global Trade ensures purity, value, and timely delivery.\"> <meta name=\"keywords\" content=\"Millets exporter in Indonesia\" />', 'Premium Millets Exporter in Indonesia | Bulk Export', '<span id=\"docs-internal-guid-030e4150-7fff-8c88-6dcf-a7871a841ee1\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:12pt;margin-bottom:12pt;\"><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">LMOK Global Trade is a trusted </span><span style=\"text-decoration-line: underline; font-size: 10pt; font-family: Arial, sans-serif; color: rgb(17, 85, 204); font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space-collapse: preserve;\"><a href=\"https://lmokglobaltrade.com/blog/millets-exporter-in-indonesia\">Millets exporter in Indonesia</a></span><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">, delivering premium-quality millets for global markets. We specialize in bulk export, ensuring freshness, purity, and consistent supply for international buyers. With strict quality control, competitive pricing, and timely shipment, LMOK Global Trade supports wholesalers, retailers, and food manufacturers worldwide. Choose us for reliable, high-grade millet exports from Indonesia.</span></p></span>', 'blog/img_694e4c94d66898.92188397.webp', '2025-12-26', 'millets-exporter-in-indonesia'),
(437, '<meta name=\"description\" content=\"Top Millets supplier in UAE offering premium, export-ready millets. LMOK Global Trade delivers quality, purity, and reliability.\"> <meta name=\"keywords\" content=\"Millets supplier in UAE\" />', 'High-Quality Millets Supplier in UAE for Export', '<span id=\"docs-internal-guid-dd5b5614-7fff-1a6c-04d8-5fbe6f5524ae\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:12pt;margin-bottom:12pt;\"><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">LMOK Global Trade is a leading </span><span style=\"text-decoration-line: underline; font-size: 10pt; font-family: Arial, sans-serif; color: rgb(17, 85, 204); font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space-collapse: preserve;\"><a href=\"https://lmokglobaltrade.com/blog/millets-supplier-in-uae\">Millets supplier in UAE</a></span><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">, delivering premium-grade millets carefully sourced and processed for export markets. We offer consistent quality, timely delivery, and competitive pricing to meet the needs of global buyers. As a trusted export partner, LMOK Global Trade ensures purity, freshness, and adherence to international standards for every millet shipment.</span></p><div bis_skin_checked=\"1\"><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\"><br></span></div></span>', 'blog/img_694e4cee720215.07810232.webp', '2025-12-26', 'millets-supplier-in-uae'),
(438, '<meta name=\"description\" content=\"Top millets exporter in Germany. LMOK Global Trade offers premium millets wholesale with quality assurance and global supply.\"> <meta name=\"keywords\" content=\"Millets exporter in Germany\" />', 'Top Millets Exporter in Germany | Wholesale Supply', '<span id=\"docs-internal-guid-5d895a2a-7fff-9f9f-cb16-05e94d9f8b2b\"><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">LMOK Global Trade is a top millets exporter in Germany, offering premium-quality millets for wholesale and bulk supply worldwide. As a trusted </span><span style=\"text-decoration-line: underline; font-size: 10pt; font-family: Arial, sans-serif; color: rgb(17, 85, 204); font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space-collapse: preserve;\"><a href=\"https://lmokglobaltrade.com/blog/millets-exporter-in-germany\">millets exporter in Germany</a></span><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">, we source, process, and export nutritious millets that meet international quality standards. Our commitment to purity, timely delivery, and competitive pricing makes us a preferred B2B partner for global importers.</span></span>', 'blog/img_694e4d1fe669c8.01178999.webp', '2025-12-26', 'millets-exporter-in-germany'),
(439, '<meta name=\"description\" content=\"Top Millets exporter in UK offering organic grains. LMOK Global Trade ensures quality, bulk supply, and global exports.\"> <meta name=\"keywords\" content=\"Millets exporter in UK\" />', 'Top Millets Exporter in UK Offering Organic Grain Supply', '<span id=\"docs-internal-guid-a20b1b1d-7fff-5f27-3bfc-423a22441352\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:12pt;margin-bottom:12pt;\"><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">LMOK Global Trade is a top </span><span style=\"text-decoration-line: underline; font-size: 11pt; font-family: Arial, sans-serif; color: rgb(17, 85, 204); font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space-collapse: preserve;\"><a href=\"https://lmokglobaltrade.com/blog/millets-exporter-in-uk\">Millets exporter in UK</a></span><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">, offering premium organic grain supply to global B2B buyers. We specialize in sourcing, processing, and exporting high-quality millets that meet international food safety standards. As a trusted Millets exporter in UK, LMOK Global Trade ensures consistent quality, bulk supply, and competitive pricing for importers, wholesalers, and food brands worldwide.</span></p></span>', 'blog/img_694e4d4ccb2570.41288181.webp', '2025-12-26', 'millets-exporter-in-uk'),
(440, '<meta name=\"description\" content=\"Top millets supplier in Malaysia. LMOK Global Trade offers premium quality millets for bulk supply and export worldwide.\"> <meta name=\"keywords\" content=\"Millets supplier in Malaysia\" />', 'Top Millets Supplier in Malaysia – Quality You Can Trust ', '<span id=\"docs-internal-guid-27dc3b08-7fff-5650-2f73-0f1c1ad1d43a\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:12pt;margin-bottom:12pt;\"><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">LMOK Global Trade is a top </span><span style=\"text-decoration-line: underline; font-size: 10pt; font-family: Arial, sans-serif; color: rgb(17, 85, 204); font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space-collapse: preserve;\"><a href=\"https://lmokglobaltrade.com/blog/millets-supplier-in-malaysia\">millets supplier in Malaysia</a></span><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">, delivering premium-quality millets sourced from trusted farms. We specialize in bulk supply and export of nutritious, naturally grown millets that meet international quality standards. As a reliable millets supplier in Malaysia, we ensure consistency, timely delivery, and competitive pricing for global buyers and distributors.</span></p><div bis_skin_checked=\"1\"><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\"><br></span></div></span>', 'blog/img_6958c5ab527e37.01825926.webp', '2026-01-03', 'millets-supplier-in-malaysia'),
(441, '<meta name=\"description\" content=\"LMOK Global Trade is a trusted millets exporter in Canada, offering premium quality millets for global importers.\"> <meta name=\"keywords\" content=\"Millets exporter in Canada\" />', 'Premium Quality Millets Exporter in Canada for Importers', '<span id=\"docs-internal-guid-857620fc-7fff-457c-dcc7-e7d89b6711ad\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:12pt;margin-bottom:12pt;\"><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">LMOK Global Trade is a premium quality </span><span style=\"text-decoration-line: underline; font-size: 10pt; font-family: Arial, sans-serif; color: rgb(17, 85, 204); font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space-collapse: preserve;\"><a href=\"https://lmokglobaltrade.com/blog/millets-exporter-in-canada\">Millets exporter in Canada</a></span><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">, supplying carefully sourced and processed millets to global importers. We ensure high nutritional value, strict quality control, and reliable bulk supply for international markets. As a trusted Millets exporter in Canada, LMOK Global Trade focuses on consistency, food safety standards, and timely worldwide delivery.</span></p></span>', 'blog/img_6958c5e282fd34.04982075.webp', '2026-01-03', 'millets-exporter-in-canada'),
(442, '<meta name=\"description\" content=\"Trusted Rice exporter in Philippines. LMOK Global Trade supplies premium quality rice to global buyers with reliable bulk exports.\"> <meta name=\"keywords\" content=\"Rice exporter in Philippines\" />', 'Trusted Rice Exporter in Philippines for Global Buyers ', '<span id=\"docs-internal-guid-4389b731-7fff-27a2-e667-a0e0225912ac\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:12pt;margin-bottom:12pt;\"><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">LMOK Global Trade is a trusted </span><span style=\"text-decoration-line: underline; font-size: 11pt; font-family: Arial, sans-serif; color: rgb(17, 85, 204); font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space-collapse: preserve;\"><a href=\"https://lmokglobaltrade.com/blog/rice-exporter-in-philippines\">Rice exporter in Philippines</a></span><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">, delivering premium-quality rice to global buyers with consistent supply and strict quality standards. We specialize in bulk exports, meeting international trade requirements with timely delivery and competitive pricing. As an experienced rice exporter, LMOK Global Trade ensures purity, freshness, and reliability for importers worldwide.</span></p><div bis_skin_checked=\"1\"><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\"><br></span></div></span>', 'blog/img_6958c6825a0958.19995791.webp', '2026-01-03', 'rice-exporter-in-philippines'),
(443, '<meta name=\"description\" content=\"LMOK Global Trade is a leading rice supplier in Saudi Arabia, offering premium rice for B2B wholesale and bulk buyers.\"> <meta name=\"keywords\" content=\"Rice supplier in Saudi Arabia\" />', 'Best Rice Supplier in Saudi Arabia for B2B Trade ', '<span id=\"docs-internal-guid-b87bf3dc-7fff-9019-f297-1f620b2b19a4\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:12pt;margin-bottom:12pt;\"><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">LMOK Global Trade is a trusted </span><span style=\"text-decoration-line: underline; font-size: 11pt; font-family: Arial, sans-serif; color: rgb(17, 85, 204); font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space-collapse: preserve;\"><a href=\"https://lmokglobaltrade.com/blog/rice-supplier-in-saudi-arabia\">rice supplier in Saudi Arabia</a></span><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">, serving B2B buyers with premium-quality rice for wholesale and bulk trade. We specialize in sourcing, processing, and supplying consistent-grade rice to importers, distributors, and food businesses. With reliable logistics, competitive pricing, and strict quality standards, LMOK Global Trade ensures long-term value and dependable supply across Saudi Arabia.</span></p></span>', 'blog/img_6958c6b03ce121.71976753.webp', '2026-01-03', 'rice-supplier-in-saudi-arabia'),
(444, '<meta name=\"description\" content=\"LMOK Global Trade is a reliable rice exporter in Malaysia offering premium long-grain and Basmati rice for global buyers.\"> <meta name=\"keywords\" content=\"Rice exporter in Malaysia\" />', 'Reliable Rice Exporter in Malaysia for Long-Grain & Basmati', '<span id=\"docs-internal-guid-5629c1a8-7fff-3a8c-61c5-41baab12d58c\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:12pt;margin-bottom:12pt;\"><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">LMOK Global Trade is a reliable </span><span style=\"text-decoration-line: underline; font-size: 10pt; font-family: Arial, sans-serif; color: rgb(17, 85, 204); font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space-collapse: preserve;\"><a href=\"https://lmokglobaltrade.com/blog/rice-exporter-in-malaysia\">rice exporter in Malaysia</a></span><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">, specializing in premium long-grain and Basmati rice for global markets. As a trusted rice exporter in Malaysia, we ensure consistent quality, hygienic processing, and timely bulk supply for importers, wholesalers, and distributors. Our commitment to international standards makes us a preferred partner for dependable rice exports worldwide.</span></p></span>', 'blog/img_6958c6e1256dd7.19662097.webp', '2026-01-03', 'rice-exporter-in-malaysia'),
(445, '<meta name=\"description\" content=\"Top rice supplier in France for B2B and wholesale buyers. LMOK Global Trade offers premium quality rice at best prices.\"> <meta name=\"keywords\" content=\"Rice supplier in France\" />', 'Top Rice Supplier in France for B2B & Wholesale Buyers ', '<span id=\"docs-internal-guid-1e9e192f-7fff-fb10-987c-8baed258a127\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:12pt;margin-bottom:12pt;\"><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">LMOK Global Trade is a top </span><span style=\"text-decoration-line: underline; font-size: 11pt; font-family: Arial, sans-serif; color: rgb(17, 85, 204); font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space-collapse: preserve;\"><a href=\"https://lmokglobaltrade.com/blog/rice-supplier-in-france\">rice supplier in France</a></span><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">, serving B2B and wholesale buyers with premium-quality rice sourced from trusted producers. As a reliable rice supplier in France, we ensure consistent supply, competitive pricing, and strict quality standards. Our solutions are tailored for importers, distributors, retailers, and food service businesses across France and global markets.</span></p></span>', 'blog/img_6958c70f829ad1.97961482.webp', '2026-01-03', 'rice-supplier-in-france'),
(446, '<meta name=\"description\" content=\"Premium quality rice exporter in Iran. LMOK Global Trade supplies high-grade rice worldwide with trusted export standards.\"> <meta name=\"keywords\" content=\"Rice exporter in Iran\" />', 'Premium Quality Rice Exporter in Iran Worldwide', '<span id=\"docs-internal-guid-760fb03a-7fff-eadf-e810-d29a91c1d5a8\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:12pt;margin-bottom:12pt;\"><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">LMOK Global Trade is a premium quality </span><span style=\"text-decoration-line: underline; font-size: 10pt; font-family: Arial, sans-serif; color: rgb(17, 85, 204); font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space-collapse: preserve;\"><a href=\"https://lmokglobaltrade.com/blog/rice-exporter-in-iran\">rice exporter in Iran</a></span><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\"> worldwide, delivering carefully sourced rice that meets international standards. As a trusted rice exporter in Iran, we specialize in bulk supply, consistent quality, and timely global shipments. Our commitment to quality control, competitive pricing, and reliable logistics makes us a preferred partner for importers and distributors across global markets.</span></p></span>', 'blog/img_6958c74973c896.31999178.webp', '2026-01-03', 'rice-exporter-in-iran'),
(447, '<meta name=\"description\" content=\"LMOK Global Trade is a reliable rice supplier in UK offering premium Basmati and Non-Basmati rice for bulk and wholesale buyers.\"> <meta name=\"keywords\" content=\"Rice supplier in UK\" />', 'Best Rice Supplier in UK for Basmati & Non-Basmati ', '<span id=\"docs-internal-guid-f128a971-7fff-c524-90a6-e6da45592b7e\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:12pt;margin-bottom:12pt;\"><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">LMOK Global Trade is a trusted </span><span style=\"text-decoration-line: underline; font-size: 11pt; font-family: Arial, sans-serif; color: rgb(17, 85, 204); font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space-collapse: preserve;\"><a href=\"https://lmokglobaltrade.com/blog/rice-supplier-in-uk\">rice supplier in UK</a></span><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">, offering premium Basmati and Non-Basmati rice sourced from reliable growers. We serve wholesalers, retailers, and bulk buyers with consistent quality, rich aroma, and competitive pricing. As an experienced rice supplier in UK, we ensure timely delivery, strict quality control, and customer-focused service for long-term business growth.</span></p></span>', 'blog/img_695b4477ed0098.01561740.webp', '2026-01-05', 'rice-supplier-in-uk'),
(448, '<meta name=\"description\" content=\"LMOK Global Trade is a trusted Screws exporter in USA supplying high-quality screws for all industries worldwide.\"> <meta name=\"keywords\" content=\"Screws exporter in USA\" />', 'High-Quality Screws Exporter in USA for All Industries', '<span id=\"docs-internal-guid-09bcc405-7fff-9b14-37f8-77d013b15d70\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:12pt;margin-bottom:12pt;\"><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">LMOK Global Trade is a </span><span style=\"text-decoration-line: underline; font-size: 11pt; font-family: Arial, sans-serif; color: rgb(17, 85, 204); font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space-collapse: preserve;\"><a href=\"https://lmokglobaltrade.com/blog/screws-exporter-in-usa\">Screws exporter in USA</a></span><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\"> delivering high-quality fasteners for all industries, including construction, automotive, engineering, and manufacturing. We ensure precision manufacturing, strict quality control, and reliable global supply. As a trusted Screws exporter in USA, LMOK Global Trade provides durable, corrosion-resistant screws that meet international standards and bulk export requirements.</span></p></span>', 'blog/img_695b44c32473d8.45349197.webp', '2026-01-05', 'screws-exporter-in-usa');
INSERT INTO `blog` (`id`, `tag`, `heading`, `content`, `image`, `date`, `slug`) VALUES
(449, '<meta name=\"description\" content=\"Leading screws supplier in Germany, LMOK Global Trade offers high-quality industrial screws for all industries.\"> <meta name=\"keywords\" content=\"Screws supplier in Germany\" />', 'Leading Screws Supplier in Germany for All Industries', '<span id=\"docs-internal-guid-41f134de-7fff-4062-b7d1-1e4bf6054a91\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:12pt;margin-bottom:12pt;\"><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">LMOK Global Trade is a leading </span><span style=\"text-decoration-line: underline; font-size: 11pt; font-family: Arial, sans-serif; color: rgb(17, 85, 204); font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space-collapse: preserve;\"><a href=\"https://lmokglobaltrade.com/blog/screws-supplier-in-germany\">screws supplier in Germany</a></span><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">, serving all industries with premium-quality industrial and construction screws. We specialize in bulk supply, consistent quality, and timely delivery for manufacturing, automotive, infrastructure, and engineering sectors. With strict quality standards and global sourcing expertise, LMOK Global Trade ensures reliable fastening solutions tailored to diverse industrial needs across Germany.</span></p></span>', 'blog/img_695cae79e6fc54.93873494.webp', '2026-01-06', 'screws-supplier-in-germany'),
(450, '<meta name=\"description\" content=\"Trusted screws exporter in France. LMOK Global Trade supplies premium industrial screws with global quality standards.\"> <meta name=\"keywords\" content=\"Screws exporter in France\" />', 'Trusted Screws Exporter in France for Industrial Use', '<span id=\"docs-internal-guid-8234ca99-7fff-a6a2-102f-b47e0afeadeb\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:12pt;margin-bottom:12pt;\"><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">LMOK Global Trade is a trusted </span><span style=\"text-decoration-line: underline; font-size: 10pt; font-family: Arial, sans-serif; color: rgb(17, 85, 204); font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space-collapse: preserve;\"><a href=\"https://lmokglobaltrade.com/blog/screws-exporter-in-france\">screws exporter in France</a></span><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">, supplying premium industrial screws for construction, manufacturing, and engineering sectors. As an experienced screws exporter in France, we ensure high-strength materials, precise threading, and consistent quality standards. Our products meet global specifications, making us a reliable partner for bulk industrial screw exports worldwide.</span></p><div bis_skin_checked=\"1\"><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\"><br></span></div></span>', 'blog/img_695caeafebfc95.80955027.webp', '2026-01-06', 'screws-exporter-in-france'),
(451, '<meta name=\"description\" content=\"Premium Screws exporter in Canada by LMOK Global Trade, offering quality fasteners, bulk supply, and global delivery.\"> <meta name=\"keywords\" content=\"Screws exporter in Canada\" />', 'Premium Screws Exporter in Canada for Global Buyers', '<span id=\"docs-internal-guid-4e797a59-7fff-83d1-a4db-84769b18a214\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:12pt;margin-bottom:12pt;\"><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">LMOK Global Trade is a </span><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">premium </span><span style=\"text-decoration-line: underline; font-size: 11pt; font-family: Arial, sans-serif; color: rgb(17, 85, 204); font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space-collapse: preserve;\"><a href=\"https://lmokglobaltrade.com/blog/screws-exporter-in-canada\">Screws exporter in Canada</a></span><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\"> serving global buyers with high-quality industrial fasteners. We specialize in durable, precision-engineered screws suitable for construction, manufacturing, and engineering applications. With strict quality control, competitive pricing, and reliable international logistics, LMOK Global Trade ensures consistent supply, timely delivery, and long-term value for B2B importers worldwide.</span></p></span>', 'blog/img_695caedbd7bfe6.03960070.webp', '2026-01-06', 'screws-exporter-in-canada'),
(452, '<meta name=\"description\" content=\"Top-quality Screws supplier in Russia by LMOK Global Trade, offering durable industrial screws for global buyers worldwide.\"> <meta name=\"keywords\" content=\"Screws supplier in Russia\" />', 'Top-Quality Screws Supplier in Russia for Global Buyers', '<span id=\"docs-internal-guid-453608c5-7fff-2463-f06c-c0ece3be1b97\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:12pt;margin-bottom:12pt;\"><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">LMOK Global Trade is a top-quality </span><span style=\"text-decoration-line: underline; font-size: 10pt; font-family: Arial, sans-serif; color: rgb(17, 85, 204); font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space-collapse: preserve;\"><a href=\"https://lmokglobaltrade.com/blog/screws-supplier-in-russia\">Screws supplier in Russia</a></span><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">, delivering durable and precision-engineered screws for global buyers. We supply a wide range of industrial and construction-grade screws designed to meet international quality standards. With reliable logistics, competitive pricing, and bulk supply capabilities, LMOK Global Trade ensures consistent quality and timely delivery worldwide.</span></p></span>', 'blog/img_695caf067df2b2.86238578.webp', '2026-01-06', 'screws-supplier-in-russia'),
(453, '<meta name=\"description\" content=\"LMOK Global Trade is a trusted fox nut exporter in USA, offering premium quality makhana for wholesale and bulk buyers.\"> <meta name=\"keywords\" content=\"Fox nut exporter in USA\" />', 'Premium Fox Nut Exporter in USA for Wholesale Markets', '<span id=\"docs-internal-guid-f6a3e830-7fff-2db6-c7df-95d8d9d702cb\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:12pt;margin-bottom:12pt;\"><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">LMOK Global Trade is a premium </span><span style=\"text-decoration-line: underline; font-size: 11pt; font-family: Arial, sans-serif; color: rgb(17, 85, 204); font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space-collapse: preserve;\"><a href=\"https://lmokglobaltrade.com/blog/fox-nut-exporter-in-usa\">Fox nut exporter in USA</a></span><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">, supplying high-quality makhana to wholesale markets worldwide. We focus on purity, freshness, and consistent grading to meet global trade standards. With reliable sourcing, competitive pricing, and timely delivery, LMOK Global Trade supports distributors, retailers, and importers seeking trusted bulk fox nut supplies across the USA.</span></p></span>', 'blog/img_695cf6220d0586.85836360.webp', '2026-01-06', 'fox-nut-exporter-in-usa'),
(454, '<meta name=\"description\" content=\"LMOK Global Trade is a trusted fox nut supplier in Canada, offering premium quality fox nuts for global bulk distribution.\"> <meta name=\"keywords\" content=\"Fox nut supplier in Canada\" />', 'Top Fox Nut Supplier in Canada for Global Distribution Hub', '<span id=\"docs-internal-guid-8028f590-7fff-b135-a70f-5c71d7606d03\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:12pt;margin-bottom:12pt;\"><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">LMOK Global Trade is a top </span><span style=\"text-decoration-line: underline; font-size: 10pt; font-family: Arial, sans-serif; color: rgb(17, 85, 204); font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space-collapse: preserve;\"><a href=\"https://lmokglobaltrade.com/blog/fox-nut-supplier-in-canada\">fox nut supplier in Canada</a></span><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">, delivering premium quality fox nuts to global markets. As a trusted fox nut supplier in Canada, we focus on consistent quality, hygienic processing, and reliable international distribution. Our global distribution hub ensures timely delivery, competitive pricing, and customized bulk supply solutions for wholesalers, retailers, and importers worldwide.</span></p></span>', 'blog/img_695cfc5aadec56.37282184.webp', '2026-01-06', 'fox-nut-supplier-in-canada'),
(455, '<meta name=\"description\" content=\"Reliable fox nut exporter in France. LMOK Global Trade supplies premium fox nuts for global importers with quality assurance.\"> <meta name=\"keywords\" content=\"Fox nut exporter in France\" />', 'Reliable Fox Nut Exporter in France for International Trade ', '<span id=\"docs-internal-guid-25c5ccec-7fff-e43b-259c-d8e30e14b4ce\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:12pt;margin-bottom:12pt;\"><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">LMOK Global Trade is a reliable </span><span style=\"text-decoration-line: underline; font-size: 10pt; font-family: Arial, sans-serif; color: rgb(17, 85, 204); font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space-collapse: preserve;\"><a href=\"https://lmokglobaltrade.com/blog/fox-nut-exporter-in-france\">fox nut exporter in France</a></span><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">, delivering premium-quality fox nuts for international trade. We focus on consistent quality, hygienic processing, and timely global shipments. As a trusted fox nut exporter in France, LMOK Global Trade serves importers, wholesalers, and distributors worldwide with bulk supply solutions that meet international food and export standards.</span></p></span>', 'blog/img_695cfc956b4da1.02009217.webp', '2026-01-06', 'fox-nut-exporter-in-france'),
(456, '<meta name=\"description\" content=\"LMOK Global Trade is a trusted fox nut supplier in Germany, providing premium fox nuts for bulk and wholesale buyers.\"> <meta name=\"keywords\" content=\"Fox nut supplier in Germany\" />', 'Top Fox Nut Supplier in Germany for Bulk & Wholesale Buyers', '<span id=\"docs-internal-guid-2da229d6-7fff-1de9-3fe3-e51d64e3ad9a\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:12pt;margin-bottom:12pt;\"><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">LMOK Global Trade is a top </span><span style=\"text-decoration-line: underline; font-size: 11pt; font-family: Arial, sans-serif; color: rgb(17, 85, 204); font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space-collapse: preserve;\"><a href=\"https://lmokglobaltrade.com/blog/fox-nut-supplier-in-germany\">fox nut supplier in Germany</a></span><span style=\"font-size: 11pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">, offering premium-quality fox nuts for bulk and wholesale buyers worldwide. As a trusted fox nut supplier in Germany, we ensure consistent quality, hygienic processing, and competitive pricing. Our products meet international food standards, making us a reliable partner for importers, distributors, and food businesses seeking long-term supply solutions.</span></p></span>', 'blog/img_695de97d376259.82895650.webp', '2026-01-07', 'fox-nut-supplier-in-germany'),
(457, '<meta name=\"description\" content=\"Premium fox nut exporter in UK. LMOK Global Trade supplies quality makhana to global buyers with reliable bulk exports.\"> <meta name=\"keywords\" content=\"Fox nut exporter in UK\" />', 'Premium Fox Nut Exporter in UK Serving Global Buyers Trade', '<span id=\"docs-internal-guid-2643350c-7fff-3880-8527-806ab0741ea3\"><p dir=\"ltr\" style=\"line-height:1.38;margin-top:12pt;margin-bottom:12pt;\"><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">LMOK Global Trade is a premium </span><span style=\"text-decoration-line: underline; font-size: 10pt; font-family: Arial, sans-serif; color: rgb(17, 85, 204); font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; text-decoration-skip-ink: none; vertical-align: baseline; white-space-collapse: preserve;\"><a href=\"https://lmokglobaltrade.com/blog/fox-nut-exporter-in-uk\">fox nut exporter in UK</a></span><span style=\"font-size: 10pt; font-family: Arial, sans-serif; color: rgb(0, 0, 0); font-variant-numeric: normal; font-variant-east-asian: normal; font-variant-alternates: normal; font-variant-position: normal; font-variant-emoji: normal; vertical-align: baseline; white-space-collapse: preserve;\">, supplying high-quality makhana to global buyers. We ensure superior sourcing, hygienic processing, and reliable bulk export solutions. As a trusted fox nut exporter in UK, LMOK Global Trade serves importers, wholesalers, and food brands with consistent quality, competitive pricing, and timely international deliveries.</span></p></span>', 'blog/img_695de9b1eff2c7.27672042.webp', '2026-01-07', 'fox-nut-exporter-in-uk');

-- --------------------------------------------------------

--
-- Table structure for table `pro`
--

CREATE TABLE `pro` (
  `id` int(100) NOT NULL,
  `name` text NOT NULL,
  `image` text NOT NULL,
  `content` text NOT NULL,
  `slug` text NOT NULL,
  `content_a` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `pro`
--

INSERT INTO `pro` (`id`, `name`, `image`, `content`, `slug`, `content_a`) VALUES
(1, 'Spices', '1.jpg', 'LMOK Global Trade exports premium-quality Indian spices known for their rich aroma, natural color, and authentic taste. Our spices are carefully sourced from renowned agricultural regions of India and processed under strict quality standards to meet international export requirements. Major spices include Dry Red Chilly and Turmeric Powder, widely used in culinary, food processing, and pharmaceutical industries across global markets.', 'spices', 'We export a wide range of premium Indian spices, sourced from reliable growers and processed under strict quality controls. Our spices are known for their rich aroma, natural color, and strong flavor.'),
(2, 'Rice', '2.jpg', 'Our rice range includes both premium Basmati Rice and quality-tested Non-Basmati Rice varieties. Known for their superior grain structure, pleasant aroma, and excellent cooking properties, our rice products are processed in hygienic facilities and packed to preserve freshness. With reliable sourcing and strict quality control, we deliver rice that meets international standards and satisfies diverse global market requirements.', 'rice', 'LMOK Global Trade supplies high-quality Indian rice suitable for both retail and bulk consumption across global markets.'),
(3, 'Pulses', '3.jpg', 'We offer a wide range of high-quality Indian pulses that are rich in protein and essential nutrients. Our pulses are thoroughly cleaned, graded, and packed to ensure purity, long shelf life, and consistent quality. They are suitable for household consumption, bulk buyers, and food processing industries worldwide.', 'pulses', 'We offer a variety of nutritious pulses sourced from trusted farms and cleaned using modern techniques to ensure quality and safety.'),
(4, 'Ground Nuts', '4.jpg', 'LMOK Global Trade supplies premium-grade Ground Nuts sourced from high-yield farms in India. Our ground nuts are valued for their high oil content, rich taste, and uniform size, making them suitable for direct consumption, oil extraction, and food processing industries. Through careful cleaning, grading, and moisture-controlled packaging, we ensure product safety, longer shelf life, and consistent export quality.', 'nuts', 'Our ground nuts are carefully selected and processed to maintain freshness and quality.'),
(5, 'nuts and oilseeds', '6.jpg', 'We export a wide range of <b>premium Indian nuts and oilseeds</b>, sourced from <b>reliable farmers</b> and processed under <b>strict quality control measures</b>. Our products are valued for their <b>natural freshness, rich taste, and high nutritional content</b>, ensuring consistent quality for international markets.\r\n\r\nOur export portfolio includes <b>groundnuts (peanuts) in raw, blanched, and roasted forms</b>, <b>cashew nuts</b>, <b>almonds</b>, <b>walnuts</b>, and <b>pistachios</b>, along with <b>sesame seeds (white, black, hulled)</b>, <b>sunflower seeds</b>, <b>mustard seeds</b>, <b>flax seeds</b>, and <b>niger seeds</b>. Each product is carefully <b>cleaned, graded, and packaged</b> to meet <b>global food safety and export standards</b>.', 'nuts-oil', 'We export a wide range of premium Indian nuts and oilseeds, sourced from reliable farmers and processed under strict quality control measures.'),
(6, 'millets and grains', '7.jpg', 'We export a premium selection of <b>Indian millets and grains</b>, sourced from <b>trusted growers</b> and processed under <b>strict quality and hygiene standards</b>. Our millets and grains are known for their <b>high nutritional value, natural purity, and authentic taste</b>, making them ideal for health-focused and global markets.\r\n\r\nOur product range includes <b>Finger Millet (Ragi)</b>, <b>Foxtail Millet</b>, <b>Little Millet</b>, <b>Pearl Millet (Bajra)</b>, <b>Kodo Millet</b>, <b>Barnyard Millet</b>, <b>Proso Millet</b>, <b>Sorghum (Jowar)</b>, <b>Quinoa</b>, and <b>Amaranth</b>. Each product is <b>carefully cleaned, graded, and packaged</b> to meet <b>international export and food safety standards</b>.', 'millets-and-grains', 'We export a premium selection of Indian millets and grains, sourced from trusted growers and processed under strict quality and hygiene standards.'),
(7, 'plantation and horticulture', '8.jpg', 'We export a diverse range of <b>premium plantation and horticulture products</b>, sourced from <b>trusted estates and growers</b> and processed under <b>strict quality and hygiene standards</b>. Our products are recognized for their <b>natural freshness, rich flavor, and consistent quality</b>, catering to international market requirements.\r\n\r\nOur product portfolio includes <b>Coconut (Fresh, Semi Husked, Dry)</b>, <b>Copra</b>, <b>Areca Nut (Betel Nut)</b>, <b>Coffee Beans (Robusta, Arabica)</b>, <b>Tea (CTC, Green, Herbal)</b>, and <b>Cocoa Beans</b>. Each product is <b>carefully selected, processed, and packaged</b> to ensure <b>maximum shelf life and compliance with global export standards</b>.', 'plantation-and-horticulture', 'We export a diverse range of premium plantation and horticulture products, sourced from trusted estates and growers and processed under strict quality and hygiene standards. '),
(8, 'fresh fruits', '9.jpg', 'We export a wide range of <b>premium Indian fresh fruits</b>, sourced from <b>trusted orchards and growers</b> and handled under <b>strict quality and hygiene standards</b>. Our fruits are known for their <b>natural freshness, rich flavor, and vibrant appearance</b>, making them ideal for global markets.\n\nOur product range includes <b>Mango (Alphonso, Banganapalli, Kesar)</b>, <b>Banana (Cavendish, Red Banana)</b>, <b>Pomegranate</b>, <b>Grapes</b>, <b>Guava</b>, <b>Papaya</b>, <b>Watermelon</b>, <b>Oranges</b>, <b>Apples</b>, and <b>Lemon</b>. Each fruit is <b>carefully harvested, sorted, and packed</b> to ensure <b>maximum freshness, flavor, and shelf life</b> for international markets.', 'fresh-fruits', 'We export a wide range of premium Indian fresh fruits, sourced from trusted orchards and growers and handled under strict quality and hygiene standards.'),
(9, 'vegetables', '10.jpg', 'We export a wide range of <b>premium Indian fresh vegetables</b>, sourced from <b>trusted farms and growers</b> and handled under <b>strict quality and hygiene standards</b>. Our vegetables are known for their <b>natural freshness, crisp texture, and rich nutritional value</b>, making them ideal for international markets.\n\nOur product range includes <b>Onion</b>, <b>Potato</b>, <b>Tomato</b>, <b>Green Chillies</b>, <b>Drumstick</b>, <b>Ladyfinger (Okra)</b>, <b>Eggplant (Brinjal)</b>, <b>Cabbage</b>, <b>Cauliflower</b>, <b>Spinach</b>, <b>Bitter Gourd</b>, and <b>Bottle Gourd</b>. Each vegetable is <b>carefully harvested, sorted, and packed</b> to ensure <b>maximum freshness, quality, and shelf life</b> for export.', 'vegetables', 'We export a wide range of premium Indian fresh vegetables, sourced from trusted farms and growers and handled under strict quality and hygiene standards.'),
(10, 'oils and extracts', '11.jpg', 'We export a premium range of <b>Indian oils and extracts</b>, sourced from <b>high-quality seeds and raw materials</b> and processed under <b>strict quality and hygiene standards</b>. Our oils are valued for their <b>natural purity, rich aroma, and superior taste</b>, meeting the requirements of global markets.\r\n\r\nOur product range includes <b>Groundnut Oil</b>, <b>Sesame Oil</b>, <b>Sunflower Oil</b>, <b>Mustard Oil</b>, <b>Coconut Oil</b>, and <b>Castor Oil</b>. Each product is <b>carefully extracted, refined, and packaged</b> to ensure <b>consistency, quality, and long shelf life</b> for export.', 'oils-and-extracts', 'We export a premium range of Indian oils and extracts, sourced from high-quality seeds and raw materials and processed under strict quality and hygiene standards. '),
(11, 'agri products', '12.jpg', 'We export a diverse range of <b>premium Indian agri products</b>, sourced from <b>trusted farms and growers</b> and processed under <b>strict quality and hygiene standards</b>. Our products are valued for their <b>natural purity, nutritional benefits, and high quality</b>, catering to international markets.\r\n\r\nOur product range includes <b>Jaggery & Jaggery Powder</b>, <b>Honey</b>, <b>Medicinal & Herbal Plants</b>, and <b>Organic Fertilizers (Neem Cake, Vermicompost)</b>. Each product is <b>carefully processed, graded, and packaged</b> to ensure <b>maximum freshness, effectiveness, and compliance with global export standards</b>.', 'agri-products', 'We export a diverse range of premium Indian agri products, sourced from trusted farms and growers and processed under strict quality and hygiene standards. ');

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE `user` (
  `id` int(50) NOT NULL,
  `name` text NOT NULL,
  `password` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`id`, `name`, `password`) VALUES
(1, 'rahul', 'hghRTTYR564654@');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `blog`
--
ALTER TABLE `blog`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `pro`
--
ALTER TABLE `pro`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `blog`
--
ALTER TABLE `blog`
  MODIFY `id` int(100) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=458;

--
-- AUTO_INCREMENT for table `pro`
--
ALTER TABLE `pro`
  MODIFY `id` int(100) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;

--
-- AUTO_INCREMENT for table `user`
--
ALTER TABLE `user`
  MODIFY `id` int(50) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
